heroku:
  stage: build
  only:
    - develop
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/joftify.git
    - git push -f heroku develop

image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test:cov
